litreview/apps/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('signup', views.signup, name="signup"),
    path('login', views.connexion, name="login"),
    path('logout', views.deconnexion, name="logout"),
    path('flux', views.flux, name="flux"),
    path('posts', views.posts, name="posts"),
    path('subscription', views.subscription, name="subscription"),
    path('unsubscription', views.unsubscription, name="unsubscription"),
    path('create_ticket', views.create_ticket, name="create_ticket"),
    path('update_ticket/<int:id>', views.update_ticket, name="update_ticket"),
    path('delete_ticket/<int:id>', views.delete_ticket, name="delete_ticket"),
    path('create_review', views.create_review, name="create_review"),
    path('view_review/<int:id>', views.view_review, name="view_review"),
    path('add_review', views.add_review, name="add_review"),
    path('update_review/<int:id>', views.update_review, name="update_review"),
    path('delete_review/<int:id>', views.delete_review, name="delete_review"),
]

litreview/litreview/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('apps/', include(('apps.urls', 'apps'), namespace='apps')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

litreview/apps/templates/apps/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/png" sizes="96x96" href="{% static 'apps/assets/favicon.ico' %}" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'apps/css/style.css' %}" />
        <title>LITReview | {% block title %}{% endblock %}</title>
    </head>
    <body>
        <header>
            {% include 'apps/header.html' %}
        </header>
        <div class="d-flex justify-content-center align-items-center">
            {% block content %}{% endblock %}
        </div>
        <footer>
            {% include 'apps/footer.html' %}
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="{% static 'apps/js/stars.js' %}"></script>
    </body>
</html>

litreview/apps/templates/apps/flux.html
{% extends 'apps/base.html' %}

{% block content %}
    <div class="cont">
        <div class="title">Flux</div>
        <a href="{% url 'apps:create_ticket' %}"><button class="myBtn">Demander une critique</button></a>
        <a href="{% url 'apps:create_review' %}"><button class="myBtn">Créer une critique</button></a>
        {% include 'apps/messages.html' %}
        {% if posts %}
            {% if paginate %}
                {% include 'apps/pagination.html' %}
            {% endif %}
            {% for post in posts %}
                {% if 'Ticket' in post.class_name %}
                    {% include 'apps/ticket_item.html' with post=post %}
                {% elif 'Review' in post.class_name %}
                    {% include 'apps/review_item.html' with post=post %}
                {% endif %}
            {% endfor %}
        {% else %}
            <p>Vous n'avez aucune critique.</p>
            <p>Vérifiez que vous suiviez bien des camarades
                <a href="{% url 'apps:subscription' %}"> ici</a>.
            </p>
            {% if paginate %}
                {% include 'apps/pagination.html' %}
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

litreview/apps/templates/apps/header.html
{% load static %}
{% load bootstrap5 %}

<div class="container">
    <div class="row">
        <div class="col-4">
            <a href="{% url 'apps:index' %}"><img src="{% static 'apps/assets/logo.png' %}" alt="..." /></a>
        </div>
        <div class="col-8">
            <div class="row align-items-center h-75">
                <div class="title">LITReview</div>
            </div>
            <div class="row h-25">
            {% if user.is_authenticated %}
                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="container">
                      <a class="navbar-brand" href="{% url 'apps:index' %}">Home</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'apps:flux' %}">Flux</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'apps:posts' %}">Posts</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'apps:subscription' %}">Abonnements</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'apps:logout' %}">Se déconnecter</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{ user.username }}</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </nav>
            {% endif %}
            </div>
        </div>
    </div>
</div>

litreview/apps/templates/apps/index.html
{% extends 'apps/base.html' %}

{% block content %}
    <div class="card">
        <h2>Bienvenue</h2>
        <p>LITReview is an application to consulte or ask for reviews about books.</p>
        <p>Create your own community and follow it.</p>
        <p>You have to signup and/or login to enter in the community and have access to the site.</p>
        <p>You can follow other community users to see their tickets or reviews.</p>
        <p>See the posts of your following community.</p>
        <p>Create or ask for a review.</p>
        <p>See your own posts to modify or delete them.</p>
    </div>
{% endblock %}

litreview/apps/templates/apps/login.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}

{% block content %}
    <div class="row">
        <div class="col col-5 card">
            <div class="title">Inscrivez-vous maintenant</div>
            <a href="{% url 'apps:signup' %}"><button class="myBtn">S'inscrire</button></a>
        </div>
        <div class="col col-5 card">
            <div class="title">Connectez-vous</div>
            <form class="form form-label" action="{% url 'apps:login' %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form AForm show_label=False %}
                <button class="myBtn" type="submit">Se connecter</button>
            </form>
        </div>
    </div>
{% endblock %}

litreview/apps/templates/apps/messages.html
{% if messages %}
    {% for message in messages %}
        <p {% if message.tags %} class="message {{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
{% endif %}

litreview/apps/templates/apps/pagination.html
<div class="container px-4 px-lg-5 mt-5 justify-content-center">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-2">
        <div class="clearfix"></div>
        <nav aria-label="...">
            <ul class="pagination">
            {% if posts.has_previous %}
                <li class="page-item">
                    <a class="btn mt-auto" href="?page=1"><i class="fa fa-chevron-left ps-1 me-1"></i></a>
                </li>
                {% if posts.previous_page_number|add:'-1' >= 1 %}
                    <li class="page-item">
                        <a class="btn mt-auto" href="?page={{ posts.previous_page_number|add:'-1' }}">{{ posts.number|add:"-2" }}</a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="btn mt-auto" href="?page={{ posts.previous_page_number }}">{{ posts.number|add:"-1" }}</a>
                </li>
            {% endif %}
                <li class="page-item active"><a class="btn btn-dark btn-outline-secondary mt-auto text-white" href="">{{ posts.number }}</a></li>
            {% if posts.has_next %}
                <li class="page-item">
                    <a class="btn mt-auto" href="?page={{ posts.next_page_number }}">{{ posts.number|add:"1" }}</a>
                </li>
                {% if posts.next_page_number|add:'1' <= posts.paginator.num_pages %}
                    <li class="page-item">
                        <a class="btn mt-auto" href="?page={{ posts.next_page_number|add:'1' }}">{{ posts.number|add:"2" }}</a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="btn mt-auto" href="?page={{ posts.paginator.num_pages }}"><i class="fa fa-chevron-right ps-1 me-1"></i></a>
                </li>
            {% endif %}
            </ul>
        </nav>
    </div>
</div>

litreview/apps/templates/apps/post_modal.html
<div class="modal fade" id="Modal{{ post.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {% include 'apps/review_item.html' with post=post only='only' %}
        </div>
        <div class="modal-footer">
          <button type="button" class="myBtn" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</div>

litreview/apps/templates/apps/review.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}

{% block content %}
    <div>
        <div class="title">{{ title }}</div>
        {% if title == 'Créer une critique' %}
            <form class="form form-label" enctype="multipart/form-data" action="{% url 'apps:create_review' %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form TForm show_label=False %}
                {% bootstrap_field RForm.headline show_label=False %}
                {% bootstrap_field RForm.body show_label=False %}
                <input id='test' type="hidden" name="val_star" value="">
                {% include 'apps/star-rating.html' %}
                <button class="myBtn" type="submit">Envoyer</button>
            </form>
        {% endif %}
        {% if title == 'Modifier une critique' %}
            <form class="form form-label" action="{% url 'apps:update_review' review.id %}" method="POST">
                {% csrf_token %}
                {% include 'apps/ticket_item.html' with post=ticket %}
                {% bootstrap_field RForm.headline show_label=False %}
                {% bootstrap_field RForm.body show_label=False %}
                <input id='test' type="hidden" name="val_star" value="{{ RForm.rating.value }}">
                {% include 'apps/star-rating.html' with rating=RForm.rating.value %}
                <button class="myBtn" type="submit">Envoyer</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

litreview/apps/templates/apps/signup.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}

{% block content %}
        <div class="card">
            <div class="title">Inscrivez-vous</div>
            <form class="form form-label" action="{% url 'apps:signup' %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form UForm show_label=False %}
                <button  class="myBtn" type="submit">S'inscrire</button>
            </form>
            <a href="{% url 'apps:index' %}"><button class="myBtn">Retourner</button></a>
            {% if messages %}
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            {% endif %}
        </div>
{% endblock %}

litreview/apps/templates/apps/star-rating.html
<div class="col star-block" id="star-block{{ post.id }}">
    <span class="fa fa-refresh star-btn" id="zero{{ post.id }}"></span>
    <span class="fa fa-star star-btn {% if rating >= 1 %}checked{% endif %}" id="first{{ post.id }}"></span>
    <span class="fa fa-star star-btn {% if rating >= 2 %}checked{% endif %}" id="second{{ post.id }}"></span>
    <span class="fa fa-star star-btn {% if rating >= 3 %}checked{% endif %}" id="third{{ post.id }}"></span>
    <span class="fa fa-star star-btn {% if rating >= 4 %}checked{% endif %}" id="fourth{{ post.id }}"></span>
    <span class="fa fa-star star-btn {% if rating >= 5 %}checked{% endif %}" id="fifth{{ post.id }}"></span>
</div>

litreview/apps/templates/apps/subscription.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}

{% block content %}
    <div class="justify-content-center">
        <table class="table table-md">
        <th colspan="3">Suivre d'autres utilisateurs</th>
            <tr>
                <form class="form" action="{% url 'apps:subscription' %}" method="POST">
                    {% csrf_token %}
                    <td class="col-5">{% bootstrap_form UForm show_label=False %}</td>
                    <td class="col-4"><button type="submit" name="Envoyer">Envoyer</button></td>
                    <td class="col-3">{% include 'apps/messages.html' %}</td>
                </form>
            </tr>
        </table>
        <table class="table table-hover table-sm">
            <th colspan="2">Abonnements</th>
            <tbody>
            {% if following_users %}
                {% for following_user in following_users %}
                    <tr>
                    <form  class="form form-label" action="{% url 'apps:unsubscription' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="followed_user_id" value="{{ following_user.followed_user.id }}">
                        <td class="col-5">{{ following_user.followed_user }}</td>
                        <td class="col-7"><button type="submit" name="Desabonner">Désabonner</button></td>
                    </form>
                    </tr>
                {% endfor %}
            {% else %}
            <td>Vous ne suivez personne</td>
            {% endif %}
            </tbody>
        </table>
        <table class="table table-hover table-sm">
            <th>Abonnés</th>
            <tbody>
            {% if followed_users %}
                {% for followed_user in followed_users %}
                <tr>
                    <td>{{ followed_user.user }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <td>Vous n êtes suivi par personne</td>
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

litreview/apps/templates/apps/ticket.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}

{% block content %}
    <div>
        <div class="title">{{ title }}</h2>
        {% include 'apps/messages.html' %}
        {% if title == 'Créer un ticket' %}
            <form class="form form-label" enctype="multipart/form-data" action="{% url 'apps:create_ticket' %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form TForm show_label=False %}
                <button class="myBtn" type="submit">Envoyer</button>
            </form>
        {% elif title == 'Modifier un ticket' %}
        <form class="form form-label" enctype="multipart/form-data" action="{% url 'apps:update_ticket' ticket.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form TForm show_label=False %}
            <button class="myBtn" type="submit">Envoyer</button>
        </form>
        {% endif %}
    </div>
{% endblock %}

litreview/apps/templates/apps/ticket_item.html
{% load bootstrap5 %}


<div class="card mb-3">
    <div class="card-header">
        <strong>{{ post.user.username }}</strong> a demandé une critique <span class="text-end blockquote-footer">{{ post.time_created }}</span>
    </div>
    <div class="card-body">
        <div class="card-title">{{ post.title }}</div>
        <div class="card-text">
            <p>{{ post.description}}</p>
            {% if post.image %}
                <img src="/media/{{ post.image }}" alt="...">
            {% endif %}
        </div>
        {% if post.user == user and title != 'Modifier une critique'%}
            <div>
                <form class="form" action="{% url 'apps:update_ticket' post.id %}" method="GET">
                    {% csrf_token %}
                    <input type="hidden" name="ticket_id" value="{{ post.id }}">
                    <button class="myBtn">Modifier le ticket</button>
                </form>
                <form class="form" action="{% url 'apps:delete_ticket' post.id %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="ticket_id" value="{{ post.id }}">
                    <button class="myBtn">Supprimer le ticket</button>
                </form>
            </div>
        {% endif %}
        {% if title != 'Modifier une critique' %}
            <ul class="list-group">
            {% for review in post.get_reviews %}
                <a class="modal-link" data-bs-toggle="modal" data-bs-target="#Modal{{ review.id }}">
                    {{ review.user.username }} a publié une critique le {{ review.time_created }}
                </a>
                {% include 'apps/post_modal.html' with post=review %}
            {% endfor %}
            </ul>
        {% endif %}
    </div>
    {% if title != 'Modifier une critique' %}
        <div class="card-footer">
            {% include 'apps/post-accordion.html' with post=post %}
        </div>
    {% endif %}
</div>        